### ISSUE TITLE
Working sound tags with over 256 permutations get truncated under default settings

### ISSUE THREAD

**Issue by Vaporeon** [Sigmmma/refinery#13]
Sound tags that go over the stock permutation limit will be truncated by Refinery when safe mode is on. The resulting tag could now also be invalid as it has permutations that still point to other permutations that no longer exist.

Example map with such a tag is [here](http://vaporeon.io/hosted/halo/archives/haloce_ost_ui.7z)
`sound/music/soundtracks/loops.sound`

**Comment by gbMichelle** [comment]
@MosesofEgypt Where is it doing this? I literally can't find it.

**Comment by gbMichelle** [comment]
@MosesofEgypt ^

**Comment by MosesofEgypt** [comment]
This is where the truncation occurs:
https://github.com/Sigmmma/reclaimer/blob/master/reclaimer/field_type_methods.py#L234

There is a similar check in the rawdata_reference parser. There is a descriptor flag you can set to disable the truncation for specific reflexives. Here is an example of where it is used:

https://github.com/Sigmmma/reclaimer/blob/master/reclaimer/hek/defs/scnr.py#L942

Just set it to True for the sound permutations reflexive
